SOL:
    priceUnit:
        - USD
    decimalPlace:
        - 2
    updateFreq: 10
    discordBotKey: OTQ2NDkxNzg5ODU3MTU3MTMw.YhffKw.3zQx1oJ7Nw0fiLIDooO1GsTdbUMaa
    guildId: 946496850104565890

BTC:
    priceUnit:
        - USD
    decimalPlace:
        - 0
    updateFreq: 60
    discordBotKey: <Add discord Bot Key>
    guildId: <Add discord server id>

ETH:
    priceUnit:
        - USD
        - BTC
    decimalPlace:
        - 2
        - 5
    updateFreq: 60
    discordBotKey: <Add discord Bot Key>
    guildId: <Add discord server id>

YFI:
    priceUnit:
        - USD
        - ETH
    decimalPlace:
        - 0
        - 2
    updateFreq: 120
    discordBotKey: <Add discord Bot Key>
    guildId: <Add discord server id>

