GBP/HKD:
    decimalPlace: 2
    updateFreq: 3600
    discordBotKey: <Add discord Bot Key>
    guildId: <Add Server ID>

USD/HKD:
    decimalPlace: 3
    updateFreq: 3600
    discordBotKey: <Add discord Bot Key>
    guildId: <Add Server ID>
